"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FLEET_SETTINGS = exports.migrateLegacyKeys = exports.DEFAULT_MARKER_KEY = exports.DEFAULT_PREFIX = exports.createHostStore = exports.createDeviceStore = exports.DEFAULT_VESSEL_SLUG = exports.createVesselStore = exports.createCloudStore = exports.createAccountStore = exports.createSettingsStore = exports.defineSetting = exports.defaultFor = exports.createRegistry = exports.urlType = exports.stringType = exports.shapeType = exports.portType = exports.oneOf = exports.numberType = exports.mmsiType = exports.listType = exports.intType = exports.hostType = exports.boolType = exports.SCOPE_ORDER = void 0;
var types_js_1 = require("./types.js");
Object.defineProperty(exports, "SCOPE_ORDER", { enumerable: true, get: function () { return types_js_1.SCOPE_ORDER; } });
var valueTypes_js_1 = require("./valueTypes.js");
Object.defineProperty(exports, "boolType", { enumerable: true, get: function () { return valueTypes_js_1.boolType; } });
Object.defineProperty(exports, "hostType", { enumerable: true, get: function () { return valueTypes_js_1.hostType; } });
Object.defineProperty(exports, "intType", { enumerable: true, get: function () { return valueTypes_js_1.intType; } });
Object.defineProperty(exports, "listType", { enumerable: true, get: function () { return valueTypes_js_1.listType; } });
Object.defineProperty(exports, "mmsiType", { enumerable: true, get: function () { return valueTypes_js_1.mmsiType; } });
Object.defineProperty(exports, "numberType", { enumerable: true, get: function () { return valueTypes_js_1.numberType; } });
Object.defineProperty(exports, "oneOf", { enumerable: true, get: function () { return valueTypes_js_1.oneOf; } });
Object.defineProperty(exports, "portType", { enumerable: true, get: function () { return valueTypes_js_1.portType; } });
Object.defineProperty(exports, "shapeType", { enumerable: true, get: function () { return valueTypes_js_1.shapeType; } });
Object.defineProperty(exports, "stringType", { enumerable: true, get: function () { return valueTypes_js_1.stringType; } });
Object.defineProperty(exports, "urlType", { enumerable: true, get: function () { return valueTypes_js_1.urlType; } });
var registry_js_1 = require("./registry.js");
Object.defineProperty(exports, "createRegistry", { enumerable: true, get: function () { return registry_js_1.createRegistry; } });
Object.defineProperty(exports, "defaultFor", { enumerable: true, get: function () { return registry_js_1.defaultFor; } });
Object.defineProperty(exports, "defineSetting", { enumerable: true, get: function () { return registry_js_1.defineSetting; } });
var store_js_1 = require("./store.js");
Object.defineProperty(exports, "createSettingsStore", { enumerable: true, get: function () { return store_js_1.createSettingsStore; } });
var cloudStore_js_1 = require("./cloudStore.js");
Object.defineProperty(exports, "createAccountStore", { enumerable: true, get: function () { return cloudStore_js_1.createAccountStore; } });
Object.defineProperty(exports, "createCloudStore", { enumerable: true, get: function () { return cloudStore_js_1.createCloudStore; } });
Object.defineProperty(exports, "createVesselStore", { enumerable: true, get: function () { return cloudStore_js_1.createVesselStore; } });
Object.defineProperty(exports, "DEFAULT_VESSEL_SLUG", { enumerable: true, get: function () { return cloudStore_js_1.DEFAULT_VESSEL_SLUG; } });
var deviceStore_js_1 = require("./deviceStore.js");
Object.defineProperty(exports, "createDeviceStore", { enumerable: true, get: function () { return deviceStore_js_1.createDeviceStore; } });
Object.defineProperty(exports, "createHostStore", { enumerable: true, get: function () { return deviceStore_js_1.createHostStore; } });
Object.defineProperty(exports, "DEFAULT_PREFIX", { enumerable: true, get: function () { return deviceStore_js_1.DEFAULT_PREFIX; } });
var migrate_js_1 = require("./migrate.js");
Object.defineProperty(exports, "DEFAULT_MARKER_KEY", { enumerable: true, get: function () { return migrate_js_1.DEFAULT_MARKER_KEY; } });
Object.defineProperty(exports, "migrateLegacyKeys", { enumerable: true, get: function () { return migrate_js_1.migrateLegacyKeys; } });
var fleet_js_1 = require("./fleet.js");
Object.defineProperty(exports, "FLEET_SETTINGS", { enumerable: true, get: function () { return fleet_js_1.FLEET_SETTINGS; } });
