"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.serializeAccumulator = exports.toPolFile = exports.trueWindAngle = exports.mergeAccumulators = exports.derivePolar = exports.addSample = exports.createPolarAccumulator = exports.compareToPlan = exports.buildAdvisory = exports.buildCorridor = exports.scanHazards = exports.NIGHT_ELEVATION_DEG = exports.isNightAt = exports.solarElevationDeg = exports.WAVE_BANDS_M = exports.WIND_BANDS_KTS = exports.encounterPeriodS = exports.summarisePassage = exports.speedToKnots = exports.currentFromComponents = exports.currentToComponents = exports.waveFromComponents = exports.waveToComponents = exports.createCurrentSampler = exports.createWaveSampler = exports.fetchMarineField = exports.fromComponents = exports.toComponents = exports.boundsForPassage = exports.createWindSampler = exports.fetchWindField = exports.landZones = exports.userZone = exports.createObstacleField = exports.compareSecondOpinion = exports.seaStateFactor = exports.angleBetween = exports.destinationPoint = exports.bearingDeg = exports.distanceNm = exports.routeIsochrone = exports.GENERIC_POLARS = exports.parsePolarFile = exports.bestVmg = exports.foldTwa = exports.boatSpeed = exports.clearForecastCache = exports.getOpenMeteoForecast = exports.formatPosition = exports.isInsideNwsCoverage = void 0;
exports.deserializeAccumulator = void 0;
var openMeteo_js_1 = require("./openMeteo.js");
Object.defineProperty(exports, "isInsideNwsCoverage", { enumerable: true, get: function () { return openMeteo_js_1.isInsideNwsCoverage; } });
Object.defineProperty(exports, "formatPosition", { enumerable: true, get: function () { return openMeteo_js_1.formatPosition; } });
Object.defineProperty(exports, "getOpenMeteoForecast", { enumerable: true, get: function () { return openMeteo_js_1.getOpenMeteoForecast; } });
Object.defineProperty(exports, "clearForecastCache", { enumerable: true, get: function () { return openMeteo_js_1.clearForecastCache; } });
var polars_js_1 = require("./polars.js");
Object.defineProperty(exports, "boatSpeed", { enumerable: true, get: function () { return polars_js_1.boatSpeed; } });
Object.defineProperty(exports, "foldTwa", { enumerable: true, get: function () { return polars_js_1.foldTwa; } });
Object.defineProperty(exports, "bestVmg", { enumerable: true, get: function () { return polars_js_1.bestVmg; } });
Object.defineProperty(exports, "parsePolarFile", { enumerable: true, get: function () { return polars_js_1.parsePolarFile; } });
Object.defineProperty(exports, "GENERIC_POLARS", { enumerable: true, get: function () { return polars_js_1.GENERIC_POLARS; } });
var routing_js_1 = require("./routing.js");
Object.defineProperty(exports, "routeIsochrone", { enumerable: true, get: function () { return routing_js_1.routeIsochrone; } });
Object.defineProperty(exports, "distanceNm", { enumerable: true, get: function () { return routing_js_1.distanceNm; } });
Object.defineProperty(exports, "bearingDeg", { enumerable: true, get: function () { return routing_js_1.bearingDeg; } });
Object.defineProperty(exports, "destinationPoint", { enumerable: true, get: function () { return routing_js_1.destinationPoint; } });
Object.defineProperty(exports, "angleBetween", { enumerable: true, get: function () { return routing_js_1.angleBetween; } });
Object.defineProperty(exports, "seaStateFactor", { enumerable: true, get: function () { return routing_js_1.seaStateFactor; } });
var secondOpinion_js_1 = require("./secondOpinion.js");
Object.defineProperty(exports, "compareSecondOpinion", { enumerable: true, get: function () { return secondOpinion_js_1.compareSecondOpinion; } });
var obstacles_js_1 = require("./obstacles.js");
Object.defineProperty(exports, "createObstacleField", { enumerable: true, get: function () { return obstacles_js_1.createObstacleField; } });
Object.defineProperty(exports, "userZone", { enumerable: true, get: function () { return obstacles_js_1.userZone; } });
Object.defineProperty(exports, "landZones", { enumerable: true, get: function () { return obstacles_js_1.landZones; } });
var windField_js_1 = require("./windField.js");
Object.defineProperty(exports, "fetchWindField", { enumerable: true, get: function () { return windField_js_1.fetchWindField; } });
Object.defineProperty(exports, "createWindSampler", { enumerable: true, get: function () { return windField_js_1.createWindSampler; } });
Object.defineProperty(exports, "boundsForPassage", { enumerable: true, get: function () { return windField_js_1.boundsForPassage; } });
Object.defineProperty(exports, "toComponents", { enumerable: true, get: function () { return windField_js_1.toComponents; } });
Object.defineProperty(exports, "fromComponents", { enumerable: true, get: function () { return windField_js_1.fromComponents; } });
var marineField_js_1 = require("./marineField.js");
Object.defineProperty(exports, "fetchMarineField", { enumerable: true, get: function () { return marineField_js_1.fetchMarineField; } });
Object.defineProperty(exports, "createWaveSampler", { enumerable: true, get: function () { return marineField_js_1.createWaveSampler; } });
Object.defineProperty(exports, "createCurrentSampler", { enumerable: true, get: function () { return marineField_js_1.createCurrentSampler; } });
Object.defineProperty(exports, "waveToComponents", { enumerable: true, get: function () { return marineField_js_1.waveToComponents; } });
Object.defineProperty(exports, "waveFromComponents", { enumerable: true, get: function () { return marineField_js_1.waveFromComponents; } });
Object.defineProperty(exports, "currentToComponents", { enumerable: true, get: function () { return marineField_js_1.currentToComponents; } });
Object.defineProperty(exports, "currentFromComponents", { enumerable: true, get: function () { return marineField_js_1.currentFromComponents; } });
Object.defineProperty(exports, "speedToKnots", { enumerable: true, get: function () { return marineField_js_1.speedToKnots; } });
var passageSummary_js_1 = require("./passageSummary.js");
Object.defineProperty(exports, "summarisePassage", { enumerable: true, get: function () { return passageSummary_js_1.summarisePassage; } });
Object.defineProperty(exports, "encounterPeriodS", { enumerable: true, get: function () { return passageSummary_js_1.encounterPeriodS; } });
Object.defineProperty(exports, "WIND_BANDS_KTS", { enumerable: true, get: function () { return passageSummary_js_1.WIND_BANDS_KTS; } });
Object.defineProperty(exports, "WAVE_BANDS_M", { enumerable: true, get: function () { return passageSummary_js_1.WAVE_BANDS_M; } });
var sun_js_1 = require("./sun.js");
Object.defineProperty(exports, "solarElevationDeg", { enumerable: true, get: function () { return sun_js_1.solarElevationDeg; } });
Object.defineProperty(exports, "isNightAt", { enumerable: true, get: function () { return sun_js_1.isNightAt; } });
Object.defineProperty(exports, "NIGHT_ELEVATION_DEG", { enumerable: true, get: function () { return sun_js_1.NIGHT_ELEVATION_DEG; } });
var corridor_js_1 = require("./corridor.js");
Object.defineProperty(exports, "scanHazards", { enumerable: true, get: function () { return corridor_js_1.scanHazards; } });
Object.defineProperty(exports, "buildCorridor", { enumerable: true, get: function () { return corridor_js_1.buildCorridor; } });
Object.defineProperty(exports, "buildAdvisory", { enumerable: true, get: function () { return corridor_js_1.buildAdvisory; } });
Object.defineProperty(exports, "compareToPlan", { enumerable: true, get: function () { return corridor_js_1.compareToPlan; } });
var polarLearning_js_1 = require("./polarLearning.js");
Object.defineProperty(exports, "createPolarAccumulator", { enumerable: true, get: function () { return polarLearning_js_1.createPolarAccumulator; } });
Object.defineProperty(exports, "addSample", { enumerable: true, get: function () { return polarLearning_js_1.addSample; } });
Object.defineProperty(exports, "derivePolar", { enumerable: true, get: function () { return polarLearning_js_1.derivePolar; } });
Object.defineProperty(exports, "mergeAccumulators", { enumerable: true, get: function () { return polarLearning_js_1.mergeAccumulators; } });
Object.defineProperty(exports, "trueWindAngle", { enumerable: true, get: function () { return polarLearning_js_1.trueWindAngle; } });
Object.defineProperty(exports, "toPolFile", { enumerable: true, get: function () { return polarLearning_js_1.toPolFile; } });
Object.defineProperty(exports, "serializeAccumulator", { enumerable: true, get: function () { return polarLearning_js_1.serializeAccumulator; } });
Object.defineProperty(exports, "deserializeAccumulator", { enumerable: true, get: function () { return polarLearning_js_1.deserializeAccumulator; } });
