"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.deserializeAccumulator = exports.serializeAccumulator = exports.toPolFile = exports.trueWindAngle = exports.mergeAccumulators = exports.derivePolar = exports.addSample = exports.createPolarAccumulator = exports.fromComponents = exports.toComponents = exports.boundsForPassage = exports.createWindSampler = exports.fetchWindField = exports.landZones = exports.userZone = exports.createObstacleField = exports.compareSecondOpinion = exports.angleBetween = exports.destinationPoint = exports.bearingDeg = exports.distanceNm = exports.routeIsochrone = exports.GENERIC_POLARS = exports.parsePolarFile = exports.bestVmg = exports.foldTwa = exports.boatSpeed = exports.clearForecastCache = exports.getOpenMeteoForecast = exports.formatPosition = exports.isInsideNwsCoverage = void 0;
var openMeteo_js_1 = require("./openMeteo.js");
Object.defineProperty(exports, "isInsideNwsCoverage", { enumerable: true, get: function () { return openMeteo_js_1.isInsideNwsCoverage; } });
Object.defineProperty(exports, "formatPosition", { enumerable: true, get: function () { return openMeteo_js_1.formatPosition; } });
Object.defineProperty(exports, "getOpenMeteoForecast", { enumerable: true, get: function () { return openMeteo_js_1.getOpenMeteoForecast; } });
Object.defineProperty(exports, "clearForecastCache", { enumerable: true, get: function () { return openMeteo_js_1.clearForecastCache; } });
var polars_js_1 = require("./polars.js");
Object.defineProperty(exports, "boatSpeed", { enumerable: true, get: function () { return polars_js_1.boatSpeed; } });
Object.defineProperty(exports, "foldTwa", { enumerable: true, get: function () { return polars_js_1.foldTwa; } });
Object.defineProperty(exports, "bestVmg", { enumerable: true, get: function () { return polars_js_1.bestVmg; } });
Object.defineProperty(exports, "parsePolarFile", { enumerable: true, get: function () { return polars_js_1.parsePolarFile; } });
Object.defineProperty(exports, "GENERIC_POLARS", { enumerable: true, get: function () { return polars_js_1.GENERIC_POLARS; } });
var routing_js_1 = require("./routing.js");
Object.defineProperty(exports, "routeIsochrone", { enumerable: true, get: function () { return routing_js_1.routeIsochrone; } });
Object.defineProperty(exports, "distanceNm", { enumerable: true, get: function () { return routing_js_1.distanceNm; } });
Object.defineProperty(exports, "bearingDeg", { enumerable: true, get: function () { return routing_js_1.bearingDeg; } });
Object.defineProperty(exports, "destinationPoint", { enumerable: true, get: function () { return routing_js_1.destinationPoint; } });
Object.defineProperty(exports, "angleBetween", { enumerable: true, get: function () { return routing_js_1.angleBetween; } });
var secondOpinion_js_1 = require("./secondOpinion.js");
Object.defineProperty(exports, "compareSecondOpinion", { enumerable: true, get: function () { return secondOpinion_js_1.compareSecondOpinion; } });
var obstacles_js_1 = require("./obstacles.js");
Object.defineProperty(exports, "createObstacleField", { enumerable: true, get: function () { return obstacles_js_1.createObstacleField; } });
Object.defineProperty(exports, "userZone", { enumerable: true, get: function () { return obstacles_js_1.userZone; } });
Object.defineProperty(exports, "landZones", { enumerable: true, get: function () { return obstacles_js_1.landZones; } });
var windField_js_1 = require("./windField.js");
Object.defineProperty(exports, "fetchWindField", { enumerable: true, get: function () { return windField_js_1.fetchWindField; } });
Object.defineProperty(exports, "createWindSampler", { enumerable: true, get: function () { return windField_js_1.createWindSampler; } });
Object.defineProperty(exports, "boundsForPassage", { enumerable: true, get: function () { return windField_js_1.boundsForPassage; } });
Object.defineProperty(exports, "toComponents", { enumerable: true, get: function () { return windField_js_1.toComponents; } });
Object.defineProperty(exports, "fromComponents", { enumerable: true, get: function () { return windField_js_1.fromComponents; } });
var polarLearning_js_1 = require("./polarLearning.js");
Object.defineProperty(exports, "createPolarAccumulator", { enumerable: true, get: function () { return polarLearning_js_1.createPolarAccumulator; } });
Object.defineProperty(exports, "addSample", { enumerable: true, get: function () { return polarLearning_js_1.addSample; } });
Object.defineProperty(exports, "derivePolar", { enumerable: true, get: function () { return polarLearning_js_1.derivePolar; } });
Object.defineProperty(exports, "mergeAccumulators", { enumerable: true, get: function () { return polarLearning_js_1.mergeAccumulators; } });
Object.defineProperty(exports, "trueWindAngle", { enumerable: true, get: function () { return polarLearning_js_1.trueWindAngle; } });
Object.defineProperty(exports, "toPolFile", { enumerable: true, get: function () { return polarLearning_js_1.toPolFile; } });
Object.defineProperty(exports, "serializeAccumulator", { enumerable: true, get: function () { return polarLearning_js_1.serializeAccumulator; } });
Object.defineProperty(exports, "deserializeAccumulator", { enumerable: true, get: function () { return polarLearning_js_1.deserializeAccumulator; } });
